name: MomentoRankVouchers
version: ${project.version}
api-version: 1.16
depend: [NBTAPI]
main: com.dnyferguson.momentorankvouchers.MomentoRankVouchers
commands:
  voucher:
    aliases: [momentorankvoucher, rankvoucher]
